DROP TABLE IF EXISTS saved_wine CASCADE;

CREATE TABLE saved_wine(
  id SERIAL PRIMARY KEY,
  user_id INT REFERENCES users(id) NOT NULL,
  wine_id INT REFERENCES wine(id) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);